/*
 * This file is generated by jOOQ.
*/
package com.jarhax.tcgatagacttagtga.db;


import com.jarhax.tcgatagacttagtga.db.tables.GlobalData;
import com.jarhax.tcgatagacttagtga.db.tables.TeamData;
import com.jarhax.tcgatagacttagtga.db.tables.TeamMembers;
import com.jarhax.tcgatagacttagtga.db.tables.Teams;
import com.jarhax.tcgatagacttagtga.db.tables.UserData;
import com.jarhax.tcgatagacttagtga.db.tables.Users;
import com.jarhax.tcgatagacttagtga.db.tables.UsersFldc;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Folding extends SchemaImpl {

    private static final long serialVersionUID = 1091539083;

    /**
     * The reference instance of <code>folding</code>
     */
    public static final Folding FOLDING = new Folding();

    /**
     * The table <code>folding.global_data</code>.
     */
    public final GlobalData GLOBAL_DATA = com.jarhax.tcgatagacttagtga.db.tables.GlobalData.GLOBAL_DATA;

    /**
     * The table <code>folding.teams</code>.
     */
    public final Teams TEAMS = com.jarhax.tcgatagacttagtga.db.tables.Teams.TEAMS;

    /**
     * The table <code>folding.team_data</code>.
     */
    public final TeamData TEAM_DATA = com.jarhax.tcgatagacttagtga.db.tables.TeamData.TEAM_DATA;

    /**
     * The table <code>folding.team_members</code>.
     */
    public final TeamMembers TEAM_MEMBERS = com.jarhax.tcgatagacttagtga.db.tables.TeamMembers.TEAM_MEMBERS;

    /**
     * The table <code>folding.users</code>.
     */
    public final Users USERS = com.jarhax.tcgatagacttagtga.db.tables.Users.USERS;

    /**
     * The table <code>folding.users_fldc</code>.
     */
    public final UsersFldc USERS_FLDC = com.jarhax.tcgatagacttagtga.db.tables.UsersFldc.USERS_FLDC;

    /**
     * The table <code>folding.user_data</code>.
     */
    public final UserData USER_DATA = com.jarhax.tcgatagacttagtga.db.tables.UserData.USER_DATA;

    /**
     * No further instances allowed
     */
    private Folding() {
        super("folding", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            GlobalData.GLOBAL_DATA,
            Teams.TEAMS,
            TeamData.TEAM_DATA,
            TeamMembers.TEAM_MEMBERS,
            Users.USERS,
            UsersFldc.USERS_FLDC,
            UserData.USER_DATA);
    }
}
