/*
 * This file is generated by jOOQ.
*/
package com.jarhax.tcgatagacttagtga.db;


import com.jarhax.tcgatagacttagtga.db.tables.GlobalData;
import com.jarhax.tcgatagacttagtga.db.tables.TeamData;
import com.jarhax.tcgatagacttagtga.db.tables.TeamMembers;
import com.jarhax.tcgatagacttagtga.db.tables.Teams;
import com.jarhax.tcgatagacttagtga.db.tables.UserData;
import com.jarhax.tcgatagacttagtga.db.tables.Users;
import com.jarhax.tcgatagacttagtga.db.tables.UsersFldc;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>folding</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index GLOBAL_DATA_PRIMARY = Indexes0.GLOBAL_DATA_PRIMARY;
    public static final Index TEAMS_PRIMARY = Indexes0.TEAMS_PRIMARY;
    public static final Index TEAM_DATA_FKIDX_87 = Indexes0.TEAM_DATA_FKIDX_87;
    public static final Index TEAM_DATA_PRIMARY = Indexes0.TEAM_DATA_PRIMARY;
    public static final Index TEAM_MEMBERS_FKIDX_67 = Indexes0.TEAM_MEMBERS_FKIDX_67;
    public static final Index TEAM_MEMBERS_FKIDX_95 = Indexes0.TEAM_MEMBERS_FKIDX_95;
    public static final Index TEAM_MEMBERS_PRIMARY = Indexes0.TEAM_MEMBERS_PRIMARY;
    public static final Index USERS_PRIMARY = Indexes0.USERS_PRIMARY;
    public static final Index USERS_FLDC_PRIMARY = Indexes0.USERS_FLDC_PRIMARY;
    public static final Index USER_DATA_FKIDX_79 = Indexes0.USER_DATA_FKIDX_79;
    public static final Index USER_DATA_PRIMARY = Indexes0.USER_DATA_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index GLOBAL_DATA_PRIMARY = Internal.createIndex("PRIMARY", GlobalData.GLOBAL_DATA, new OrderField[] { GlobalData.GLOBAL_DATA.DATE }, true);
        public static Index TEAMS_PRIMARY = Internal.createIndex("PRIMARY", Teams.TEAMS, new OrderField[] { Teams.TEAMS.TEAM_ID }, true);
        public static Index TEAM_DATA_FKIDX_87 = Internal.createIndex("fkIdx_87", TeamData.TEAM_DATA, new OrderField[] { TeamData.TEAM_DATA.TEAM_ID }, false);
        public static Index TEAM_DATA_PRIMARY = Internal.createIndex("PRIMARY", TeamData.TEAM_DATA, new OrderField[] { TeamData.TEAM_DATA.DATE, TeamData.TEAM_DATA.TEAM_ID }, true);
        public static Index TEAM_MEMBERS_FKIDX_67 = Internal.createIndex("fkIdx_67", TeamMembers.TEAM_MEMBERS, new OrderField[] { TeamMembers.TEAM_MEMBERS.TEAM_ID }, false);
        public static Index TEAM_MEMBERS_FKIDX_95 = Internal.createIndex("fkIdx_95", TeamMembers.TEAM_MEMBERS, new OrderField[] { TeamMembers.TEAM_MEMBERS.USER_ID }, false);
        public static Index TEAM_MEMBERS_PRIMARY = Internal.createIndex("PRIMARY", TeamMembers.TEAM_MEMBERS, new OrderField[] { TeamMembers.TEAM_MEMBERS.TEAM_MEMBER_ID }, true);
        public static Index USERS_PRIMARY = Internal.createIndex("PRIMARY", Users.USERS, new OrderField[] { Users.USERS.USER_ID }, true);
        public static Index USERS_FLDC_PRIMARY = Internal.createIndex("PRIMARY", UsersFldc.USERS_FLDC, new OrderField[] { UsersFldc.USERS_FLDC.USER_ID }, true);
        public static Index USER_DATA_FKIDX_79 = Internal.createIndex("fkIdx_79", UserData.USER_DATA, new OrderField[] { UserData.USER_DATA.USER_ID }, false);
        public static Index USER_DATA_PRIMARY = Internal.createIndex("PRIMARY", UserData.USER_DATA, new OrderField[] { UserData.USER_DATA.DATE, UserData.USER_DATA.USER_ID }, true);
    }
}
