/*
 * This file is generated by jOOQ.
*/
package com.jarhax.tcgatagacttagtga.db;


import com.jarhax.tcgatagacttagtga.db.tables.GlobalData;
import com.jarhax.tcgatagacttagtga.db.tables.TeamData;
import com.jarhax.tcgatagacttagtga.db.tables.TeamMembers;
import com.jarhax.tcgatagacttagtga.db.tables.Teams;
import com.jarhax.tcgatagacttagtga.db.tables.UserData;
import com.jarhax.tcgatagacttagtga.db.tables.Users;
import com.jarhax.tcgatagacttagtga.db.tables.UsersFldc;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in folding
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>folding.global_data</code>.
     */
    public static final GlobalData GLOBAL_DATA = com.jarhax.tcgatagacttagtga.db.tables.GlobalData.GLOBAL_DATA;

    /**
     * The table <code>folding.teams</code>.
     */
    public static final Teams TEAMS = com.jarhax.tcgatagacttagtga.db.tables.Teams.TEAMS;

    /**
     * The table <code>folding.team_data</code>.
     */
    public static final TeamData TEAM_DATA = com.jarhax.tcgatagacttagtga.db.tables.TeamData.TEAM_DATA;

    /**
     * The table <code>folding.team_members</code>.
     */
    public static final TeamMembers TEAM_MEMBERS = com.jarhax.tcgatagacttagtga.db.tables.TeamMembers.TEAM_MEMBERS;

    /**
     * The table <code>folding.users</code>.
     */
    public static final Users USERS = com.jarhax.tcgatagacttagtga.db.tables.Users.USERS;

    /**
     * The table <code>folding.users_fldc</code>.
     */
    public static final UsersFldc USERS_FLDC = com.jarhax.tcgatagacttagtga.db.tables.UsersFldc.USERS_FLDC;

    /**
     * The table <code>folding.user_data</code>.
     */
    public static final UserData USER_DATA = com.jarhax.tcgatagacttagtga.db.tables.UserData.USER_DATA;
}
