-- MySQL Script generated by MySQL Workbench
-- Fri Jun  8 13:15:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema folding
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `folding` ;

-- -----------------------------------------------------
-- Schema folding
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `folding` DEFAULT CHARACTER SET latin1 ;
USE `folding` ;

-- -----------------------------------------------------
-- Table `folding`.`global_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `folding`.`global_data` ;

CREATE TABLE IF NOT EXISTS `folding`.`global_data` (
  `DATE` DATETIME NOT NULL,
  `FOLDERS_TOTAL` INT(11) NOT NULL,
  `POINTS_TOTAL` BIGINT(20) NOT NULL,
  `WORK_UNITS_TOTAL` BIGINT(20) NOT NULL,
  `FLDC_FOLDERS_TOTAL` INT(11) NOT NULL,
  PRIMARY KEY (`DATE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `folding`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `folding`.`teams` ;

CREATE TABLE IF NOT EXISTS `folding`.`teams` (
  `TEAM_ID` INT(11) NOT NULL,
  `NAME` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`TEAM_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `folding`.`team_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `folding`.`team_data` ;

CREATE TABLE IF NOT EXISTS `folding`.`team_data` (
  `DATE` DATETIME NOT NULL,
  `TEAM_ID` INT(11) NOT NULL,
  `POINTS_TOTAL` BIGINT(20) NOT NULL,
  `WORK_UNITS_TOTAL` BIGINT(20) NOT NULL,
  `FLDC_FOLDERS_TOTAL` INT(11) NOT NULL,
  PRIMARY KEY (`DATE`, `TEAM_ID`),
  INDEX `fkIdx_87` (`TEAM_ID` ASC),
  CONSTRAINT `FK_87`
    FOREIGN KEY (`TEAM_ID`)
    REFERENCES `folding`.`teams` (`TEAM_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `folding`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `folding`.`users` ;

CREATE TABLE IF NOT EXISTS `folding`.`users` (
  `USER_ID` INT(11) NOT NULL,
  `NAME` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `folding`.`team_members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `folding`.`team_members` ;

CREATE TABLE IF NOT EXISTS `folding`.`team_members` (
  `TEAM_MEMBER_ID` INT(11) NOT NULL,
  `TEAM_ID` INT(11) NOT NULL,
  `USER_ID` INT(11) NOT NULL,
  PRIMARY KEY (`TEAM_MEMBER_ID`),
  INDEX `fkIdx_67` (`TEAM_ID` ASC),
  INDEX `fkIdx_95` (`USER_ID` ASC),
  CONSTRAINT `FK_67`
    FOREIGN KEY (`TEAM_ID`)
    REFERENCES `folding`.`teams` (`TEAM_ID`),
  CONSTRAINT `FK_95`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `folding`.`users` (`USER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `folding`.`user_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `folding`.`user_data` ;

CREATE TABLE IF NOT EXISTS `folding`.`user_data` (
  `DATE` DATETIME NOT NULL,
  `USER_ID` INT(11) NOT NULL,
  `POINTS_TOTAL` BIGINT(20) NOT NULL,
  `WORK_UNITS_TOTAL` BIGINT(20) NOT NULL,
  PRIMARY KEY (`DATE`, `USER_ID`),
  INDEX `fkIdx_79` (`USER_ID` ASC),
  CONSTRAINT `FK_79`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `folding`.`users` (`USER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `folding`.`users_fldc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `folding`.`users_fldc` ;

CREATE TABLE IF NOT EXISTS `folding`.`users_fldc` (
  `USER_ID` INT(11) NOT NULL,
  `ADDRESS` VARCHAR(34) NULL DEFAULT NULL,
  `CREDIT_NEW` DOUBLE NULL DEFAULT NULL,
  `TOKEN` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  CONSTRAINT `USER_ID`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `folding`.`users` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
