/*
 * This file is generated by jOOQ.
*/
package com.jarhax.tcgatagacttagtga.db.tables.records;


import com.jarhax.tcgatagacttagtga.db.tables.GlobalData;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GlobalDataRecord extends UpdatableRecordImpl<GlobalDataRecord> implements Record5<Timestamp, Integer, Long, Long, Integer> {

    private static final long serialVersionUID = 792336145;

    /**
     * Setter for <code>folding.global_data.DATE</code>.
     */
    public void setDate(Timestamp value) {
        set(0, value);
    }

    /**
     * Getter for <code>folding.global_data.DATE</code>.
     */
    public Timestamp getDate() {
        return (Timestamp) get(0);
    }

    /**
     * Setter for <code>folding.global_data.FOLDERS_TOTAL</code>.
     */
    public void setFoldersTotal(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>folding.global_data.FOLDERS_TOTAL</code>.
     */
    public Integer getFoldersTotal() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>folding.global_data.POINTS_TOTAL</code>.
     */
    public void setPointsTotal(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>folding.global_data.POINTS_TOTAL</code>.
     */
    public Long getPointsTotal() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>folding.global_data.WORK_UNITS_TOTAL</code>.
     */
    public void setWorkUnitsTotal(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>folding.global_data.WORK_UNITS_TOTAL</code>.
     */
    public Long getWorkUnitsTotal() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>folding.global_data.FLDC_FOLDERS_TOTAL</code>.
     */
    public void setFldcFoldersTotal(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>folding.global_data.FLDC_FOLDERS_TOTAL</code>.
     */
    public Integer getFldcFoldersTotal() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Timestamp> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Timestamp, Integer, Long, Long, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Timestamp, Integer, Long, Long, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field1() {
        return GlobalData.GLOBAL_DATA.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return GlobalData.GLOBAL_DATA.FOLDERS_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return GlobalData.GLOBAL_DATA.POINTS_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return GlobalData.GLOBAL_DATA.WORK_UNITS_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return GlobalData.GLOBAL_DATA.FLDC_FOLDERS_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component1() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getFoldersTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getPointsTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getWorkUnitsTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getFldcFoldersTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value1() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getFoldersTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getPointsTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getWorkUnitsTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getFldcFoldersTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GlobalDataRecord value1(Timestamp value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GlobalDataRecord value2(Integer value) {
        setFoldersTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GlobalDataRecord value3(Long value) {
        setPointsTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GlobalDataRecord value4(Long value) {
        setWorkUnitsTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GlobalDataRecord value5(Integer value) {
        setFldcFoldersTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GlobalDataRecord values(Timestamp value1, Integer value2, Long value3, Long value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GlobalDataRecord
     */
    public GlobalDataRecord() {
        super(GlobalData.GLOBAL_DATA);
    }

    /**
     * Create a detached, initialised GlobalDataRecord
     */
    public GlobalDataRecord(Timestamp date, Integer foldersTotal, Long pointsTotal, Long workUnitsTotal, Integer fldcFoldersTotal) {
        super(GlobalData.GLOBAL_DATA);

        set(0, date);
        set(1, foldersTotal);
        set(2, pointsTotal);
        set(3, workUnitsTotal);
        set(4, fldcFoldersTotal);
    }
}
