/*
 * This file is generated by jOOQ.
*/
package com.jarhax.tcgatagacttagtga.db.tables.records;


import com.jarhax.tcgatagacttagtga.db.tables.TeamData;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamDataRecord extends UpdatableRecordImpl<TeamDataRecord> implements Record5<Date, Integer, Long, Long, Integer> {

    private static final long serialVersionUID = 10238942;

    /**
     * Setter for <code>folding.team_data.DATE</code>.
     */
    public void setDate(Date value) {
        set(0, value);
    }

    /**
     * Getter for <code>folding.team_data.DATE</code>.
     */
    public Date getDate() {
        return (Date) get(0);
    }

    /**
     * Setter for <code>folding.team_data.TEAM_ID</code>.
     */
    public void setTeamId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>folding.team_data.TEAM_ID</code>.
     */
    public Integer getTeamId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>folding.team_data.POINTS_TOTAL</code>.
     */
    public void setPointsTotal(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>folding.team_data.POINTS_TOTAL</code>.
     */
    public Long getPointsTotal() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>folding.team_data.WORK_UNITS_TOTAL</code>.
     */
    public void setWorkUnitsTotal(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>folding.team_data.WORK_UNITS_TOTAL</code>.
     */
    public Long getWorkUnitsTotal() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>folding.team_data.FLDC_FOLDERS_TOTAL</code>.
     */
    public void setFldcFoldersTotal(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>folding.team_data.FLDC_FOLDERS_TOTAL</code>.
     */
    public Integer getFldcFoldersTotal() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Date, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Date, Integer, Long, Long, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Date, Integer, Long, Long, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field1() {
        return TeamData.TEAM_DATA.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TeamData.TEAM_DATA.TEAM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return TeamData.TEAM_DATA.POINTS_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return TeamData.TEAM_DATA.WORK_UNITS_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TeamData.TEAM_DATA.FLDC_FOLDERS_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component1() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getTeamId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getPointsTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getWorkUnitsTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getFldcFoldersTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value1() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTeamId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getPointsTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getWorkUnitsTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getFldcFoldersTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeamDataRecord value1(Date value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeamDataRecord value2(Integer value) {
        setTeamId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeamDataRecord value3(Long value) {
        setPointsTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeamDataRecord value4(Long value) {
        setWorkUnitsTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeamDataRecord value5(Integer value) {
        setFldcFoldersTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeamDataRecord values(Date value1, Integer value2, Long value3, Long value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamDataRecord
     */
    public TeamDataRecord() {
        super(TeamData.TEAM_DATA);
    }

    /**
     * Create a detached, initialised TeamDataRecord
     */
    public TeamDataRecord(Date date, Integer teamId, Long pointsTotal, Long workUnitsTotal, Integer fldcFoldersTotal) {
        super(TeamData.TEAM_DATA);

        set(0, date);
        set(1, teamId);
        set(2, pointsTotal);
        set(3, workUnitsTotal);
        set(4, fldcFoldersTotal);
    }
}
