/*
 * This file is generated by jOOQ.
*/
package com.jarhax.tcgatagacttagtga.db.tables.records;


import com.jarhax.tcgatagacttagtga.db.tables.TeamMembers;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamMembersRecord extends UpdatableRecordImpl<TeamMembersRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 45549122;

    /**
     * Setter for <code>folding.team_members.TEAM_MEMBER_ID</code>.
     */
    public void setTeamMemberId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>folding.team_members.TEAM_MEMBER_ID</code>.
     */
    public Integer getTeamMemberId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>folding.team_members.TEAM_ID</code>.
     */
    public void setTeamId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>folding.team_members.TEAM_ID</code>.
     */
    public Integer getTeamId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>folding.team_members.USER_ID</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>folding.team_members.USER_ID</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TeamMembers.TEAM_MEMBERS.TEAM_MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TeamMembers.TEAM_MEMBERS.TEAM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TeamMembers.TEAM_MEMBERS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getTeamMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getTeamId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getTeamMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTeamId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeamMembersRecord value1(Integer value) {
        setTeamMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeamMembersRecord value2(Integer value) {
        setTeamId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeamMembersRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeamMembersRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamMembersRecord
     */
    public TeamMembersRecord() {
        super(TeamMembers.TEAM_MEMBERS);
    }

    /**
     * Create a detached, initialised TeamMembersRecord
     */
    public TeamMembersRecord(Integer teamMemberId, Integer teamId, Integer userId) {
        super(TeamMembers.TEAM_MEMBERS);

        set(0, teamMemberId);
        set(1, teamId);
        set(2, userId);
    }
}
