/*
 * This file is generated by jOOQ.
*/
package com.jarhax.tcgatagacttagtga.db.tables.records;


import com.jarhax.tcgatagacttagtga.db.tables.UsersFldc;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersFldcRecord extends UpdatableRecordImpl<UsersFldcRecord> implements Record5<Date, Integer, String, Double, String> {

    private static final long serialVersionUID = 1092214990;

    /**
     * Setter for <code>folding.users_fldc.DATE</code>.
     */
    public void setDate(Date value) {
        set(0, value);
    }

    /**
     * Getter for <code>folding.users_fldc.DATE</code>.
     */
    public Date getDate() {
        return (Date) get(0);
    }

    /**
     * Setter for <code>folding.users_fldc.USER_ID</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>folding.users_fldc.USER_ID</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>folding.users_fldc.ADDRESS</code>.
     */
    public void setAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>folding.users_fldc.ADDRESS</code>.
     */
    public String getAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>folding.users_fldc.CREDIT_NEW</code>.
     */
    public void setCreditNew(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>folding.users_fldc.CREDIT_NEW</code>.
     */
    public Double getCreditNew() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>folding.users_fldc.TOKEN</code>.
     */
    public void setToken(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>folding.users_fldc.TOKEN</code>.
     */
    public String getToken() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Date> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Date, Integer, String, Double, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Date, Integer, String, Double, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field1() {
        return UsersFldc.USERS_FLDC.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UsersFldc.USERS_FLDC.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UsersFldc.USERS_FLDC.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return UsersFldc.USERS_FLDC.CREDIT_NEW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return UsersFldc.USERS_FLDC.TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component1() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getCreditNew();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value1() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getCreditNew();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersFldcRecord value1(Date value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersFldcRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersFldcRecord value3(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersFldcRecord value4(Double value) {
        setCreditNew(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersFldcRecord value5(String value) {
        setToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersFldcRecord values(Date value1, Integer value2, String value3, Double value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersFldcRecord
     */
    public UsersFldcRecord() {
        super(UsersFldc.USERS_FLDC);
    }

    /**
     * Create a detached, initialised UsersFldcRecord
     */
    public UsersFldcRecord(Date date, Integer userId, String address, Double creditNew, String token) {
        super(UsersFldc.USERS_FLDC);

        set(0, date);
        set(1, userId);
        set(2, address);
        set(3, creditNew);
        set(4, token);
    }
}
