/*
 * This file is generated by jOOQ.
*/
package com.jarhax.tcgatagacttagtga.db.tables;


import com.jarhax.tcgatagacttagtga.db.Folding;
import com.jarhax.tcgatagacttagtga.db.Indexes;
import com.jarhax.tcgatagacttagtga.db.Keys;
import com.jarhax.tcgatagacttagtga.db.tables.records.TeamMembersRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamMembers extends TableImpl<TeamMembersRecord> {

    private static final long serialVersionUID = 1846693969;

    /**
     * The reference instance of <code>folding.team_members</code>
     */
    public static final TeamMembers TEAM_MEMBERS = new TeamMembers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TeamMembersRecord> getRecordType() {
        return TeamMembersRecord.class;
    }

    /**
     * The column <code>folding.team_members.TEAM_ID</code>.
     */
    public final TableField<TeamMembersRecord, Integer> TEAM_ID = createField("TEAM_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>folding.team_members.USER_ID</code>.
     */
    public final TableField<TeamMembersRecord, Integer> USER_ID = createField("USER_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>folding.team_members</code> table reference
     */
    public TeamMembers() {
        this(DSL.name("team_members"), null);
    }

    /**
     * Create an aliased <code>folding.team_members</code> table reference
     */
    public TeamMembers(String alias) {
        this(DSL.name(alias), TEAM_MEMBERS);
    }

    /**
     * Create an aliased <code>folding.team_members</code> table reference
     */
    public TeamMembers(Name alias) {
        this(alias, TEAM_MEMBERS);
    }

    private TeamMembers(Name alias, Table<TeamMembersRecord> aliased) {
        this(alias, aliased, null);
    }

    private TeamMembers(Name alias, Table<TeamMembersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Folding.FOLDING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TEAM_MEMBERS_FKIDX_67, Indexes.TEAM_MEMBERS_FKIDX_95, Indexes.TEAM_MEMBERS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TeamMembersRecord> getPrimaryKey() {
        return Keys.KEY_TEAM_MEMBERS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TeamMembersRecord>> getKeys() {
        return Arrays.<UniqueKey<TeamMembersRecord>>asList(Keys.KEY_TEAM_MEMBERS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TeamMembersRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TeamMembersRecord, ?>>asList(Keys.FK_67, Keys.FK_95);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeamMembers as(String alias) {
        return new TeamMembers(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeamMembers as(Name alias) {
        return new TeamMembers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TeamMembers rename(String name) {
        return new TeamMembers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TeamMembers rename(Name name) {
        return new TeamMembers(name, null);
    }
}
