/*
 * This file is generated by jOOQ.
*/
package com.jarhax.tcgatagacttagtga.db.tables;


import com.jarhax.tcgatagacttagtga.db.Folding;
import com.jarhax.tcgatagacttagtga.db.Indexes;
import com.jarhax.tcgatagacttagtga.db.Keys;
import com.jarhax.tcgatagacttagtga.db.tables.records.UserDataRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserData extends TableImpl<UserDataRecord> {

    private static final long serialVersionUID = -2141046268;

    /**
     * The reference instance of <code>folding.user_data</code>
     */
    public static final UserData USER_DATA = new UserData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserDataRecord> getRecordType() {
        return UserDataRecord.class;
    }

    /**
     * The column <code>folding.user_data.DATE</code>.
     */
    public final TableField<UserDataRecord, Date> DATE = createField("DATE", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>folding.user_data.USER_ID</code>.
     */
    public final TableField<UserDataRecord, Integer> USER_ID = createField("USER_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>folding.user_data.POINTS_TOTAL</code>.
     */
    public final TableField<UserDataRecord, Long> POINTS_TOTAL = createField("POINTS_TOTAL", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>folding.user_data.WORK_UNITS_TOTAL</code>.
     */
    public final TableField<UserDataRecord, Long> WORK_UNITS_TOTAL = createField("WORK_UNITS_TOTAL", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>folding.user_data</code> table reference
     */
    public UserData() {
        this(DSL.name("user_data"), null);
    }

    /**
     * Create an aliased <code>folding.user_data</code> table reference
     */
    public UserData(String alias) {
        this(DSL.name(alias), USER_DATA);
    }

    /**
     * Create an aliased <code>folding.user_data</code> table reference
     */
    public UserData(Name alias) {
        this(alias, USER_DATA);
    }

    private UserData(Name alias, Table<UserDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserData(Name alias, Table<UserDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Folding.FOLDING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USER_DATA_FKIDX_79, Indexes.USER_DATA_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserDataRecord> getPrimaryKey() {
        return Keys.KEY_USER_DATA_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserDataRecord>> getKeys() {
        return Arrays.<UniqueKey<UserDataRecord>>asList(Keys.KEY_USER_DATA_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UserDataRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserDataRecord, ?>>asList(Keys.FK_79);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserData as(String alias) {
        return new UserData(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserData as(Name alias) {
        return new UserData(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserData rename(String name) {
        return new UserData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserData rename(Name name) {
        return new UserData(name, null);
    }
}
